import { IconClipboard, IconDownload, IconExternalLink, IconFileDescription, IconPlayerPause, IconPlayerPlay, IconPlus, IconRadar, IconSettings, IconShieldLock } from "@tabler/icons-react";
import type { LeadEngineState } from "@/hooks/useLeadEngineState";
import { downloadText, formatDate, VIEW_LABELS } from "./model";
import { ImportAndReclassificationTools } from "./ImportAndReclassificationTools";
import styles from "../LeadEngineApp.module.css";

export function AdvancedToolsView({ state }: { state: LeadEngineState }) {
  const { activeCampaign, activeCampaignId, businessCampaigns, campaignDiscoverySources, engine, pending } = state;
  const dueSourceCount = campaignDiscoverySources.filter((source) => source.status === "active" && source.cadence !== "manual" && source.nextRunAt && new Date(source.nextRunAt) <= new Date()).length;
  return <section className={styles.toolWorkspace} aria-label={VIEW_LABELS.advanced}>
    <div className={styles.toolHeader}><div><span className={styles.sectionKicker}>MAINTENANCE & FALLBACKS</span><h1>高级工具</h1><p>日常自动找客户不需要这些入口；仅在扩充来源、手工诊断、补录或恢复时使用。</p></div><IconSettings size={34} /></div>
    <label className={styles.contextPicker}>维护或导入到 Campaign<select value={activeCampaignId} onChange={(event) => state.setActiveCampaignId(event.target.value)}><option value="">请选择 Campaign</option>{businessCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select></label>
    <details className={styles.advancedSection} open><summary><span><IconRadar size={20} />来源维护与手工诊断</span><small>{campaignDiscoverySources.length} 个来源 · {dueSourceCount} 个到期</small></summary><div className={styles.toolGrid}>
      <section className={styles.toolSection}><div className={styles.sectionTitleRow}><h2><IconPlus size={20} />添加已批准来源</h2><button className={styles.secondaryButton} type="button" disabled={pending || engine?.status !== "running"} onClick={() => void state.controlEngine("run_batch")}><IconRadar size={17} />受控补采一批</button></div><p className={styles.muted}>只补充公开协会或展商目录。搜索结果不能直接作为合格证据；手工补采仍走同一自动引擎与当日审计账本。</p><form className={styles.formGrid} onSubmit={state.addDiscoverySource}><label className={styles.field}>来源名称<input name="name" required maxLength={160} placeholder="例如：某眼镜展公开展商名录" /></label><label className={styles.field}>运行频率<select name="cadence" defaultValue="daily"><option value="manual">仅手动</option><option value="daily">每天</option><option value="weekly">每周</option></select></label><label className={[styles.field, styles.fieldWide].join(" ")}>公开目录网址<input name="sourceUrl" type="url" required maxLength={2048} placeholder="https://…" /></label><label className={styles.field}>每批最多候选<input name="maxCandidates" type="number" min="1" max="20" defaultValue="20" /></label><button className={styles.primaryButton} type="submit" disabled={!activeCampaignId || activeCampaign?.status !== "active" || pending}>{activeCampaign?.status !== "active" ? "先启用 Campaign" : "保存来源"}</button></form><div className={styles.discoveryBoundary}><b><IconShieldLock size={18} />采集边界</b><span>不采集个人姓名、个人邮箱或手机号</span><span>不猜邮箱，不生成或发送开发信</span><span>不自动批准，不写入生产 CRM</span></div></section>
      <section className={styles.toolSection}><h2>来源控制</h2><div className={styles.discoverySourceList}>{campaignDiscoverySources.map((source) => <article key={source.id}><div className={styles.discoverySourceHead}><div><b>{source.name}</b><a href={source.sourceUrl} target="_blank" rel="noreferrer">{source.normalizedDomain}<IconExternalLink size={14} /></a></div><span className={source.enabled && source.status === "active" ? styles.sourceActive : styles.sourcePaused}>{source.enabled && source.status === "active" ? `${source.tier}级 · 已启用` : "已暂停"}</span></div><dl className={styles.discoveryMeta}><div><dt>类型 / 区域</dt><dd>{source.sourceType} · {source.region}</dd></div><div><dt>解析器</dt><dd>{source.parserKey} v{source.parserVersion}</dd></div><div><dt>发现 / 合格 / 重复</dt><dd>{source.lastDiscoveredCount} / {source.lastQualifiedCount} / {source.lastDuplicateCount}</dd></div><div><dt>失败次数</dt><dd>{source.failureCount}</dd></div><div><dt>robots / 访问</dt><dd>{source.robotsStatus} · {source.requiresLogin ? "需登录" : source.isPaid ? "付费" : "公开免费"}</dd></div><div><dt>下次到期</dt><dd>{source.status === "paused" ? "已暂停" : source.cadence === "manual" ? "仅手动" : formatDate(source.nextRunAt)}</dd></div></dl>{source.lastError ? <p className={styles.runError}>{source.lastError}</p> : null}<div className={styles.discoveryActions}><button className={styles.primaryButton} type="button" disabled={pending || !source.enabled || source.status !== "active" || source.requiresLogin || source.isPaid || activeCampaign?.status !== "active"} onClick={() => void state.runDiscovery(source.id)}><IconPlayerPlay size={17} />立即采集</button><button className={styles.secondaryButton} type="button" disabled={pending} onClick={() => void state.toggleDiscoverySource(source)}>{source.status === "active" ? <IconPlayerPause size={17} /> : <IconPlayerPlay size={17} />}{source.status === "active" ? "暂停" : "恢复"}</button></div></article>)}{!campaignDiscoverySources.length ? <div className={styles.emptyCompact}><IconRadar size={28} /><b>尚未添加来源</b><span>先启用 Campaign，再添加公开行业目录。</span></div> : null}</div></section>
    </div></details>
    <details className={styles.advancedSection}><summary><span><IconClipboard size={20} />人工调研任务书</span><small>来源扩充或外部研究时使用</small></summary>{activeCampaign ? <div className={styles.researchLayout}><section className={styles.toolSection}><div className={styles.sectionTitleRow}><h2>本地语言检索词</h2><button className={styles.secondaryButton} type="button" onClick={() => downloadText(activeCampaign.name + "-research-brief.md", activeCampaign.researchBrief)}><IconDownload size={18} />下载任务书</button></div><div className={styles.keywordList}>{activeCampaign.searchKeywords.map((item) => <article key={item.locale + "-" + item.keyword}><span>{item.locale}</span><div><b>{item.keyword}</b><small>{item.purpose}</small></div></article>)}</div></section><section className={styles.toolSection}><h2><IconFileDescription size={20} />任务书预览</h2><pre className={styles.briefPreview}>{activeCampaign.researchBrief}</pre></section></div> : <div className={styles.emptyState}><b>请先创建 Campaign</b><button type="button" onClick={() => state.setActiveView("campaign")}>前往 Campaign</button></div>}</details>
    <ImportAndReclassificationTools state={state} />
  </section>;
}
