import { IconAlertTriangle, IconFileExport, IconPlayerPause, IconPlayerPlay, IconRadar, IconSettings, IconX } from "@tabler/icons-react";
import type { LeadEngineState } from "@/hooks/useLeadEngineState";
import { formatDate, VIEW_LABELS } from "./model";
import styles from "../LeadEngineApp.module.css";

export function AutomaticDiscoveryView({ state }: { state: LeadEngineState }) {
  const { activeBusinessCampaigns, campaignById, discoverySourceById, engine, globalDiscoveryRuns, globalSourceOverview, latestRun, openAlerts, pending, todayRemaining, todayTarget, totalApprovedCount, workspace } = state;
  return <section className={styles.toolWorkspace} aria-label={VIEW_LABELS.discovery}>
    <div className={styles.toolHeader}><div><span className={styles.sectionKicker}>PERSISTENT DAILY DISCOVERY</span><h1>全局自动找客户</h1><p>无需先选择 Campaign。系统根据所有运行中 Campaign 的国家、客户类型与产品条件轮换公开来源，再按证据自动归类；无法可靠归类的客户进入待分配。</p></div><IconRadar size={34} /></div>
    <section className={styles.engineDashboard}>
      <div className={styles.engineControl}><div><span>当前运行状态</span><b data-status={engine?.status || "stopped"}>{engine?.status === "running" ? "已标记运行" : engine?.status === "paused" ? "已暂停" : "已停止"}</b><small>时区：{engine?.timezone || "Asia/Shanghai"} · 后台持续运行需已启用 Cron</small></div><div className={styles.engineActions}><button className={styles.primaryButton} type="button" disabled={pending || engine?.status === "running" || !activeBusinessCampaigns.length} onClick={() => void state.controlEngine("start")}><IconPlayerPlay size={18} />开始自动找客户</button><button className={styles.secondaryButton} type="button" disabled={pending || engine?.status !== "running"} onClick={() => void state.controlEngine("pause")}><IconPlayerPause size={18} />暂停</button><button className={styles.secondaryButton} type="button" disabled={pending || engine?.status !== "paused"} onClick={() => void state.controlEngine("resume")}><IconPlayerPlay size={18} />恢复</button><button className={styles.secondaryButton} type="button" disabled={pending || !engine || engine.status === "stopped"} onClick={() => void state.controlEngine("stop")}><IconX size={18} />停止</button></div></div>
      <div className={styles.engineMetrics}><article><span>今日目标</span><b>{todayTarget?.targetCount || engine?.dailyTarget || 20}</b><small>自动筛选合格客户</small></article><article className={styles.metricSuccess}><span>今日已完成</span><b>{todayTarget?.qualifiedCount || 0}</b><small>强制准入通过且有商务联系方式</small></article><article className={todayRemaining ? styles.metricWarning : styles.metricSuccess}><span>今日仍缺</span><b>{todayRemaining}</b><small>{todayTarget?.sourceExhausted ? "可用来源已耗尽" : "后续批次继续补采"}</small></article><article><span>重复 / 淘汰 / 失败</span><b>{todayTarget?.duplicateCount || 0} / {todayTarget?.mandatoryGateFailedCount || 0} / {todayTarget?.failedCount || 0}</b><small>均不计入每日目标</small></article></div>
      <div className={styles.engineTimeline}><span>最近运行：<b>{formatDate(engine?.lastRunAt)}</b></span><span>下次运行：<b>{formatDate(engine?.nextRunAt)}</b></span><span>当前来源：<b>{latestRun ? discoverySourceById.get(latestRun.sourceId)?.name || "来源已删除" : "等待下一批"}</b></span><span>后台目标：<b>{latestRun ? campaignById.get(latestRun.campaignId)?.name || "Campaign 已删除" : "自动轮换"}</b></span><span>原始 / 解析 / 官网 / 有效联系：<b>{todayTarget?.rawDiscoveredCount || 0} / {todayTarget?.parsedCount || 0} / {todayTarget?.websiteVerifiedCount || 0} / {todayTarget?.validContactCount || 0}</b></span></div>
      {todayTarget?.deficitReason || engine?.lastError ? <div className={styles.engineAlert}><IconAlertTriangle size={19} /><span>{todayTarget?.deficitReason || engine?.lastError}</span></div> : null}
      {openAlerts.length ? <div className={styles.alertList}>{openAlerts.slice(0, 5).map((alert) => <article key={alert.id} data-severity={alert.severity}><b>{alert.severity === "critical" ? "重要告警" : "来源提醒"}</b><span>{alert.message}</span><small>{formatDate(alert.createdAt)}</small></article>)}</div> : null}
      <div className={styles.engineExports}><span>自动合格客户可在审核台按 Campaign 查看证据；人工批准后才能导出。</span><button className={styles.secondaryButton} type="button" disabled={!totalApprovedCount} onClick={() => state.setActiveView("export")}><IconFileExport size={17} />前往 CRM 导出</button></div>
    </section>
    <div className={styles.discoveryPrinciples}><article><b>预置官方来源免费运行</b><span>付费搜索和 GPT provider 有接口但默认关闭、无密钥也可运行</span></article><article><b>每批最多 5 个候选</b><span>尊重 robots 与来源限流；失败后下一批自动切换来源</span></article><article><b>人工批准仍是联系闸门</b><span>自动合格客户进入待审核，不发送邮件、不写生产 CRM</span></article></div>
    <section className={[styles.toolSection, styles.sourceOverview].join(" ")}><div className={styles.sectionTitleRow}><h2>来源运行概览</h2><button className={styles.secondaryButton} type="button" onClick={() => state.setActiveView("advanced")}><IconSettings size={17} />管理来源</button></div><div className={styles.sourceOverviewGrid}>{globalSourceOverview.map((source) => <article key={source.id}><div><b>{source.name}</b><span className={source.enabled && source.status === "active" ? styles.sourceActive : styles.sourcePaused}>{source.enabled && source.status === "active" ? `${source.tier}级 · 已启用` : "已暂停"}</span></div><p>{source.activeCampaignCount} 个 Campaign 使用</p><small>{source.region} · {source.cadence === "manual" ? "仅手动" : `下次：${formatDate(source.nextRunAt)}`}</small></article>)}{!globalSourceOverview.length ? <div className={styles.emptyCompact}><IconRadar size={28} /><b>尚未准备来源</b><span>启用 Campaign 后，引擎会按市场准备官方来源。</span></div> : null}</div></section>
    <section className={[styles.toolSection, styles.discoveryHistory].join(" ")}><div className={styles.sectionTitleRow}><h2>采集批次日志</h2><span className={styles.muted}>每一次访问、去重、排除和失败都会保留</span></div><div className={styles.runList}>{globalDiscoveryRuns.map((run) => { const runItems = workspace.discoveryItems.filter((item) => item.runId === run.id); return <article key={run.id}><div className={styles.runSummary}><div><b>{discoverySourceById.get(run.sourceId)?.name || "已删除来源"}</b><span>{campaignById.get(run.campaignId)?.name || "Campaign 已删除"} · {formatDate(run.startedAt)} · {run.trigger === "scheduled" ? "定时" : "手动"}</span></div><strong data-status={run.status}>{run.status === "completed" ? "完成" : run.status === "partial" ? "部分完成" : run.status === "failed" ? "失败" : "运行中"}</strong></div><div className={styles.runMetrics}><span>原始发现 <b>{run.rawDiscoveredCount ?? run.discoveredCount}</b></span><span>成功解析 <b>{run.parsedCount || 0}</b></span><span>官网核验 <b>{run.websiteVerifiedCount || 0}</b></span><span>有效联系 <b>{run.validContactCount || 0}</b></span><span>自动合格 <b>{run.qualifiedCount || 0}</b></span><span>重复 <b>{run.duplicateCount}</b></span><span>准入失败 <b>{run.mandatoryGateFailedCount || run.excludedCount}</b></span><span>采集失败 <b>{run.failedCount}</b></span></div>{run.errorSummary ? <pre className={styles.runError}>{run.errorSummary}</pre> : null}{runItems.length ? <details className={styles.runDetails}><summary>查看本批明细（{runItems.length}）</summary><div>{runItems.slice(0, 20).map((item) => <a key={item.id} href={item.websiteUrl} target="_blank" rel="noreferrer"><span>{item.outcome === "imported" ? "新增" : item.outcome === "duplicate" ? "重复" : item.outcome === "excluded" ? "排除" : "失败"}</span><b>{item.companyName || item.normalizedDomain}</b><small>{item.reason}</small></a>)}</div></details> : null}</article>; })}{!globalDiscoveryRuns.length ? <p className={styles.muted}>尚无采集批次。开始引擎后等待服务器定时运行；手工诊断入口位于高级工具。</p> : null}</div></section>
  </section>;
}
