import { IconAlertTriangle, IconCheck, IconClock, IconExternalLink, IconRadar, IconTrash, IconX } from "@tabler/icons-react";
import type { LeadEngineState } from "@/hooks/useLeadEngineState";
import { compactRisk, companySignal, CONFIDENCE_LABELS, customerTypeLabel, formatDate, jsonList, localizedCompanyType, localizedCountry, SCORE_LABELS, STATUS_LABELS } from "./model";
import styles from "../LeadEngineApp.module.css";

export function LeadReviewDrawer({ state }: { state: LeadEngineState }) {
  const { approvalGaps, assignmentCampaignId, businessCampaigns, campaignById, detailLoading, leadDetail, pending, reviewNotes } = state;
  if (detailLoading) return <aside className={styles.drawer} aria-label="当前客户证据与审核"><div className={styles.emptyState}><IconClock size={26} /><b>正在加载客户证据…</b></div></aside>;
  if (!leadDetail) return <aside className={styles.drawer} aria-label="当前客户证据与审核"><div className={styles.emptyState}><b>选择一家公司查看证据</b></div></aside>;
  const { claims, company, contactVerifications, domains, lead, memberships, reviews, scoreDimensions, scoreRun, sources } = leadDetail;
  return <aside className={styles.drawer} aria-label="当前客户证据与审核">
    <div className={styles.drawerHeader}><div><span>当前客户</span><h2>{company.companyName}</h2></div><button type="button" aria-label="关闭客户详情" onClick={() => state.setDrawerOpen(false)}><IconX size={22} /></button></div>
    <div className={styles.drawerBody}>
      <dl className={styles.drawerFacts}><div><dt>类型</dt><dd>{customerTypeLabel(company)}</dd></div><div><dt>国家</dt><dd>{localizedCountry(company.country)}</dd></div><div><dt>评分</dt><dd className={styles.drawerScore}>{lead.currentScore}</dd></div></dl>
      <section className={styles.coverageBlock}><div><span>证据覆盖</span><b>{lead.evidenceCoverage}%</b></div><progress max="100" value={lead.evidenceCoverage}>{lead.evidenceCoverage}%</progress><div className={styles.confidenceRow}><span>可信度</span><b>{CONFIDENCE_LABELS[lead.scoreConfidence] || lead.scoreConfidence}</b></div></section>
      <section className={styles.decisionSummary}><article><span>关键采购信号</span><p>{localizedCompanyType(company.companyType)}，官网公开{companySignal(company).replaceAll(" · ", "、")}</p></article><article className={styles.riskSummary}><span><IconAlertTriangle size={17} /> 风险</span><p>{compactRisk(lead)}</p></article></section>
      <details className={styles.drawerDetails}><summary>完整评分 <span>{scoreRun?.rubricVersion || "版本未记录"}</span></summary><div className={styles.scoreList}>{scoreDimensions.map((item) => <article key={item.id}><div><b>{SCORE_LABELS[item.dimension] || item.dimension}</b><strong>{item.score}/{item.maxScore}</strong></div>{item.positiveReason ? <p><IconCheck size={15} />{item.positiveReason}</p> : null}{item.negativeReason ? <p className={styles.negativeReason}><IconAlertTriangle size={15} />{item.negativeReason}</p> : null}</article>)}</div></details>
      <details className={styles.drawerDetails}><summary>证据来源 <span>{sources.length} 条</span></summary><div className={styles.sourceList}>{sources.map((source) => <a key={source.id} href={source.sourceUrl} target="_blank" rel="noreferrer"><div><b>{source.pageTitle || source.sourceType}</b><IconExternalLink size={16} /></div><p>{source.evidenceSummary || "无来源摘要"}</p><small>{source.confidence} · 核验于 {formatDate(source.retrievedAt)}</small></a>)}{!sources.length ? <p className={styles.muted}>没有来源，不能批准。</p> : null}{claims.slice(0, 5).map((claim) => <article key={claim.id}><span>{claim.evidenceKind}</span><b>{claim.claimSummary}</b></article>)}</div></details>
      <details className={styles.drawerDetails}><summary>公司资料 <span>{domains.length ? "已解析域名" : "域名待补"}</span></summary><dl className={styles.compactFacts}><div><dt>官网</dt><dd>{company.website ? <a href={company.website} target="_blank" rel="noreferrer">{company.primaryDomain || company.website}<IconExternalLink size={14} /></a> : "未记录"}</dd></div><div><dt>域名</dt><dd>{domains.map((domain) => domain.normalizedDomain).join(" · ") || "未记录"}</dd></div><div><dt>客户类型</dt><dd>{customerTypeLabel(company)}</dd></div><div><dt>公司角色</dt><dd>{company.companyRole || "未记录"}</dd></div><div><dt>产品方向</dt><dd>{jsonList(company.productDirectionsJson).join(" · ") || "未记录"}</dd></div><div><dt>规模 / 定位</dt><dd>{[company.companySize, company.pricePosition].filter(Boolean).join(" · ") || "待 AI 核验"}</dd></div><div><dt>产品 / 品牌</dt><dd>{[...jsonList(company.productsJson), ...jsonList(company.brandsJson)].join(" · ") || "未记录"}</dd></div><div><dt>推荐产品</dt><dd>{jsonList(lead.recommendedProductsJson).join(" · ") || "未记录"}</dd></div><div><dt>公开商务渠道</dt><dd>{company.businessEmail || company.contactChannel || "未记录"}</dd></div><div><dt>来源</dt><dd>{[company.sourceType, company.sourceName].filter(Boolean).join(" · ") || "未记录"}</dd></div><div><dt>发现 / 核验</dt><dd>{formatDate(company.firstDiscoveredAt)} / {formatDate(company.lastVerifiedAt)}</dd></div></dl>{leadDetail.contactCount ? <p className={styles.muted}>已保存 {leadDetail.contactCount} 条候选联系人记录；本页默认不展示个人联系方式。</p> : null}</details>
      <details className={styles.drawerDetails} open><summary>匹配 Campaign <span>{memberships.filter((membership) => membership.matchStatus !== "stale").length} 个当前归属</span></summary><div className={styles.auditList}>{memberships.map((membership) => <article key={membership.leadId}><div><b>{campaignById.get(membership.campaignId)?.name || membership.campaignName}{company.primaryCampaignId === membership.campaignId ? " · 主 Campaign" : ""}</b><span>{membership.matchStatus === "stale" ? "历史归属" : membership.assignmentType === "manual" ? "人工归属" : "证据自动匹配"} · 优先级 {membership.strategyPriority}</span>{membership.matchReason ? <p>{membership.matchReason}</p> : null}</div></article>)}</div></details>
      <details className={styles.drawerDetails} open={contactVerifications.length > 0}><summary>商务联系方式核验 <span>{contactVerifications.length} 条</span></summary><div className={styles.sourceList}>{contactVerifications.map((contact) => <a key={contact.id} href={contact.sourceUrl} target="_blank" rel="noreferrer"><div><b>{contact.contactType} · {contact.status === "valid" ? "有效" : "未通过"}</b><IconExternalLink size={16} /></div><p>{contact.contactValue || "未保存具体值"}</p><small>{contact.sameCompanyDomain ? "企业同域" : "可信官方来源"} · 核验于 {formatDate(contact.verifiedAt)}</small></a>)}{!contactVerifications.length ? <p className={styles.muted}>没有公开商务联系方式核验记录，不能计入每日目标。</p> : null}</div></details>
      {reviews.length ? <details className={styles.drawerDetails}><summary>审核历史 <span>{reviews.length} 条</span></summary><div className={styles.auditList}>{reviews.map((item) => <article key={item.id}><div><b>{STATUS_LABELS[item.decision] || item.decision}</b><span>{formatDate(item.createdAt)}</span></div><p>{item.notes || "未附备注"}</p></article>)}</div></details> : null}
    </div>
    <div className={styles.reviewDock}>
      {lead.campaignId === "system:unassigned" ? <div className={styles.assignmentBox}><label>先分配到 Campaign<select value={assignmentCampaignId} onChange={(event) => state.setAssignmentCampaignId(event.target.value)}><option value="">请选择目标 Campaign</option>{businessCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select></label><button type="button" className={styles.primaryButton} disabled={pending || !assignmentCampaignId} onClick={() => void state.assignSelectedLead()}>确认分配</button></div> : null}
      <label>审核备注<input value={reviewNotes} onChange={(event) => state.setReviewNotes(event.target.value)} placeholder="淘汰时必须填写原因" /></label>
      {approvalGaps.length ? <div className={styles.gapSummary}><IconAlertTriangle size={17} /><span>{approvalGaps.slice(0, 3).join(" · ")}</span></div> : <div className={styles.readySummary}><IconCheck size={17} /><span>已满足批准闸门，仍需你做最终判断。</span></div>}
      <button type="button" className={styles.approveButton} onClick={() => void state.review("approved")} disabled={pending || approvalGaps.length > 0}>{approvalGaps.length ? "证据不足，暂不能批准" : "批准进入导出池"}</button>
      <button type="button" className={styles.rejectButton} onClick={() => void state.review("rejected")} disabled={pending}><IconTrash size={18} />淘汰</button>
      <button type="button" className={styles.keepButton} onClick={() => void state.review("needs_review")} disabled={pending}><IconClock size={17} />保留待审核</button>
      <details className={styles.reviewMaintenance}><summary>高级维护</summary><button type="button" className={styles.keepButton} onClick={() => void state.reverifySelectedLead()} disabled={pending || !company.website}><IconRadar size={17} />重新核验官网与联系方式</button></details>
    </div>
  </aside>;
}
